

version: '3.5'

services:
  orthanc:
    image: jodogne/orthanc-plugins:latest
    hostname: orthanc
    command: /run/secrets/
    volumes:
      # Config
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
      - ./WorklistsDatabase:/WorklistsDatabase
    ports:
      - '4242:4242' # DICOM
      - '8042:8042' # Web
    secrets:
      - orthanc.json
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    restart: unless-stopped

secrets:
  orthanc.json:
    file: ./config/orthanc.json
